// <auto-generated />
namespace EZWork.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class EditTable_Review : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditTable_Review));
        
        string IMigrationMetadata.Id
        {
            get { return "202008240949504_EditTable_Review"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
