// <auto-generated />
namespace EZWork.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addLevel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addLevel));
        
        string IMigrationMetadata.Id
        {
            get { return "202009050719496_addLevel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
